"""
Strategy signal models.
"""
from enum import Enum
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class SignalDirection(str, Enum):
    """Signal direction."""
    YES = "yes"
    NO = "no"
    NONE = "none"


class SignalStrength(str, Enum):
    """Signal strength/confidence."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class StrategySignal(BaseModel):
    """Trading signal generated by a strategy."""

    # Strategy info
    strategy_name: str = Field(..., description="Name of the strategy")

    # Market
    ticker: str = Field(..., description="Target market ticker")

    # Signal
    direction: SignalDirection = Field(..., description="Trade direction")
    strength: SignalStrength = Field(..., description="Signal strength")

    # Probability & Edge
    true_probability: float = Field(..., ge=0, le=1, description="Strategy's probability estimate")
    market_probability: float = Field(..., ge=0, le=1, description="Current market probability")
    edge: float = Field(..., description="Estimated edge (true_prob - market_prob)")

    # Position Sizing
    kelly_fraction: float = Field(..., ge=0, description="Kelly fraction to use")
    recommended_quantity: int = Field(..., ge=0, description="Recommended position size in contracts")
    recommended_price: Optional[float] = Field(None, ge=0, le=1, description="Recommended limit price")

    # Risk
    confidence: float = Field(..., ge=0, le=1, description="Overall confidence score")
    max_loss: float = Field(..., ge=0, description="Maximum potential loss")
    max_gain: float = Field(..., ge=0, description="Maximum potential gain")

    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = Field(None, description="When this signal expires")

    # Additional context
    reasoning: Optional[str] = Field(None, description="Human-readable reasoning")
    metrics: dict = Field(default_factory=dict, description="Additional strategy-specific metrics")

    @property
    def is_valid(self) -> bool:
        """Check if signal is still valid."""
        if self.direction == SignalDirection.NONE:
            return False
        if self.expires_at and datetime.utcnow() > self.expires_at:
            return False
        return True

    @property
    def has_edge(self) -> bool:
        """Check if signal has positive edge."""
        return abs(self.edge) > 0.02  # Minimum 2% edge

    class Config:
        json_schema_extra = {
            "example": {
                "strategy_name": "kelly_volatility",
                "ticker": "KXSOL15M-24FEB15-1430-T249.50",
                "direction": "yes",
                "strength": "high",
                "true_probability": 0.65,
                "market_probability": 0.55,
                "edge": 0.10,
                "kelly_fraction": 0.25,
                "recommended_quantity": 15,
                "recommended_price": 0.56,
                "confidence": 0.85,
                "max_loss": 840,
                "max_gain": 660,
                "reasoning": "High volatility arbitrage opportunity with 10% edge"
            }
        }
